spring:
  application:
    name: joblens

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/joblens
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true