spring:
  application:
    name: joblens

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/joblens
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1
          temperature: 0.2